services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-secondhand
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-secondhand:3306/secondhandDB?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: secondhandadmin
      SPRING_DATASOURCE_PASSWORD: $231&ssdaDHT*/1
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-secondhand
    restart: always
    environment:
      MYSQL_DATABASE: secondhandDB
      MYSQL_USER: secondhandadmin
      MYSQL_PASSWORD: $231&ssdaDHT*/1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_SSL_CIPHER: TLSv1.2
    ports:
      - "3366:3306"
    expose:
      - "3306"
