services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-secondhand
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-secondhand:3306/secondhandDB?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-secondhand
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_SSL_CIPHER: ${MYSQL_SSL_CIPHER}
    ports:
      - "3366:3306"
    expose:
      - "3306"
